services:
  - type: web
    name: erp_vittavento
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      flask db upgrade &&
      gunicorn -b 0.0.0.0:10000 run:app