"""Add article hierarchy

Revision ID: 2637db4e838e
Revises: 2ef323c45a65
Create Date: 2025-05-04 23:23:12.808155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2637db4e838e'
down_revision = '2ef323c45a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_components',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'component_id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'articles', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_id')

    op.drop_table('article_components')
    # ### end Alembic commands ###
