"""Добавлены ArticleAttribute и ArticleAttributeValue

Revision ID: 2ef323c45a65
Revises: baa50e94725d
Create Date: 2025-05-03 17:50:05.507913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ef323c45a65'
down_revision = 'baa50e94725d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_attribute_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['article_attributes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_attribute_values')
    op.drop_table('article_attributes')
    # ### end Alembic commands ###
