"""Add characteristics and additional_properties to Article

Revision ID: d15d5d6e1242
Revises: 2637db4e838e
Create Date: 2025-05-05 03:08:51.785125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd15d5d6e1242'
down_revision = '2637db4e838e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('characteristics', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('additional_properties', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('additional_properties')
        batch_op.drop_column('characteristics')

    # ### end Alembic commands ###
